# -*- coding: utf-8 -*-
"""End to End ML Classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vFRF_guw2U4x54R1jGJ_N7LDo8lXOKAT
"""

import pandas as pd
import numpy as np

df = pd.read_csv('/content/placement.csv')

df.head()

df.shape

df = df.iloc[:,1:]

df.head()

"""#Steps

# 0. Preprocess + EDA + Features Selection
# 1. Extract input and output cols
# 2. Scale the values
# 3. Train test split
# 4. Train the model
# 5. Evaluate the model/models selection
# 6. Deploy the model

"""

import matplotlib.pyplot as plt

plt.scatter(df['cgpa'], df['iq'],c=df['placement'])

x = df.iloc[:,0:2]
y = df.iloc[:,-1]

x

y

y.shape

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.1)

x_train

y_train

x_test

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

x_train = scaler.fit_transform(x_train)

x_train

x_test = scaler.transform(x_test)

x_test

from sklearn.linear_model import LogisticRegression

clf = LogisticRegression()

#model training
clf.fit(x_train, y_train)

y_pred = clf.predict(x_test)

y_test

from sklearn.metrics import accuracy_score

#from lib- mlxtend
from mlxtend.plotting import plot_decision_regions

plot_decision_regions(x_train, y_train.values, clf=clf, legend=2)

import pickle

pickle.dump(clf, open('model.pkl','wb'))

